export const experiences = [
  {
    id: 1,
    type: "work",
    company: "Verv",
    position: "Full-stack Developer",
    location: "Highbury Corner, N5 1RA, London , UK",
    period: "Dec 2024 - Present",
    duration: "1+ years",
    description:
      "As a full-stack Developer, I am responsible for designing, developing, and optimizing scalable web applications, ensuring seamless data management, and collaborating with cross-functional teams to enhance system performance and user experience.",
    achievements: [
      "Develop and maintain scalable frontend components using frameworks like React.js and Next.js.",
      "Build and manage robust backend systems using Node.js or Python (Django, FastAPI).",
      "Design and implement RESTful APIs and/or GraphQL endpoints.",
      "Integrate and manage relational and non-relational databases such as PostgreSQL, MySQL, MongoDB, or DynamoDB.",
      "Mentor junior developers and conduct code reviews to ensure code quality and best practices.",
      "Optimise application performance for maximum speed and scalability.",
      "Collaborate with cross-functional teams, including designers, QA, and product managers.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Postgresql",
      "MongoDB",
    ],
    website: "https://www.linkedin.com/company/vervsocial/posts/?feedView=all",
    featured: true,
  },
  {
    id: 2,
    type: "work",
    company: "Shafi Consultancy Limited",
    position: "Back End Developer",
    location: "Sylhet, Bangladesh",
    period: "Jun 2023 - Dec 2024",
    duration: "1 year 7 months",
    description: "I was responsible for",
    achievements: [
      "Design and develop scalable APIs using Python (Django DRF) and Node.js (Express) for data-driven applications.",
      "Design and develop web applications for data visualization and project management using React, Node.js, and Python.",
      "Write modular and reusable Python scripts for automation, data processing, and ETL tasks.",
      "Develop secure authentication/authorization using JWT and session-based strategies with Node.js and Python.",
      "Integrate APIs with PostgreSQL and MongoDB for dynamic data visualization dashboards.",
      "Provide training and mentorship to other programmers.",
      "Conduct training sessions on Python to enhance team skill sets.",
      "Read and analyze client requirements for data transformations and statistical analysis.",
      "Develop and validate programs in appropriate software to deliver outputs within agreed timelines and budget.",
      "Update analysis dataset specifications based on client requirements.",
      "Develop and improve statistical programming processes for efficiency and accuracy.",
    ],
    technologies: [
      "Node.js",
      "Express.js",
      "Next.js",
      "Django REST Framework",
      "React.js",
      "Git",
    ],
    website: "https://www.shaficonsultancy.com",
    featured: false,
  },
  {
    id: 3,
    type: "work",
    company: "Shafi Consultancy Limited",
    position: "Statistical Programmer 1",
    location: "Sylhet, Bangladesh",
    period: "Feb 2022 - May 2023",
    duration: "1 year 4 months",
    description: "I was responsible for",
    achievements: [
      "Automate processes and enhance workflow efficiency using Python and SAS.",
      "Develop data visualization solutions using Python and SAS to present insights effectively.",
      "Read and analyze client requirements for data transformations and statistical analysis.",
      "Develop, write, and validate programs in appropriate software to deliver outputs within agreed timelines and budget.",
      "Perform independent quality control (QC) procedures to ensure data accuracy and integrity.",
      "Develop independent validation programs while maintaining professional programming standards.",
      "Generate study-specific macros for different study purposes to improve efficiency.",
    ],
    technologies: [
      "Python",
      "SAS",
      "Data Visualization",
      "Data Analysis",
      "Quality Assurance",
    ],
    website: "https://www.shaficonsultancy.com",
    featured: false,
  },
  {
    id: 4,
    type: "work",
    company: "Shafi Consultancy Limited",
    position: "Trainee Statistical Programmer",
    location: "Sylhet, Bangladesh",
    period: "Aug 2021 - Jan 2022",
    duration: "6 months",
    description: "I was responsible for",
    achievements: [
      "Read, understand, and complete training on all assigned SOPs, Guidelines, and Working Instructions.",
      "Received training on clinical trials, data manipulation, SAS programming, and NONMEM.",
      "Developed and maintained well-documented programs for statistical analysis.",
      "Gained hands-on experience in data processing and statistical programming techniques.",
      "Learned best practices for ensuring data integrity and compliance with industry standards.",
    ],
    technologies: [
      "Python",
      "SAS",
      "Data Visualization",
      "Data Analysis",
      "Quality Assurance",
    ],
    website: "https://www.shaficonsultancy.com",
    featured: false,
  },
  {
    id: 5,
    type: "education",
    company: "Shahjalal University of Science and Technologyy",
    position: "Bachelor of Science in Mathematics",
    location: "Sylhet, Bangladesh",
    period: "2015 - 2019",
    duration: "4 years",
    description:
      "Focused on Mathematics. Explored the intersection of technology and art through various projects and research.",
    achievements: [
      "Led the Euclid Programming Club with 200+ members",
    ],
    technologies: [
      "Python",
      "C",
      "Machine Learning",
      "Data Structures",
      "Algorithms",
    ],
    website: "https://www.sust.edu",
    featured: false,
  },
];

export const skills = [
  {
    category: "Frontend",
    items: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Tailwind CSS",
      "Vanila CSS"
    ],
  },
  {
    category: "Creative",
    items: [
      "Axios",
      "Tanstack Query",
      "React-hook-form",
      "Zod",
      "JWT"
    ],
  },
  {
    category: "Backend",
    items: ["Node.js", "Express.js","Python", "PostgreSQL", "MongoDB"],
  },
  {
    category: "Tools",
    items: ["Git", "GitHub", "VS Code"],
  },
];

export const categories = [
  { key: "all", label: "All Experience" },
  { key: "work", label: "Work" },
  { key: "education", label: "Education" },
];
