export const experiences = [
  {
    id: 1,
    type: "work",
    company: "Verv",
    position: "Senior Full-stack Developer",
    location: "Highbury Corner, N5 1RA, London , UK",
    period: "Dec 2025 - Present",
    duration: "1+ years",
    description:
      "As a Senior Full-stack Developer, I am responsible for designing, developing, and optimizing scalable web applications, ensuring seamless data management, and collaborating with cross-functional teams to enhance system performance and user experience.",
    achievements: [
      "Building and maintaining scalable frontend components with React.js and Next.js to deliver responsive, user-friendly interfaces.",
      "Developing and optimizing backend systems with Node.js, Express.js, and Prisma ORM to ensure scalability, reliability, and security.",
      "Designing and implementing RESTful API endpoints to enable seamless communication between services.",
      "Integrating and managing relational (PostgreSQL) and NoSQL (MongoDB) databases to ensure secure, efficient, and scalable data handling.",
      "Leading projects across the full lifecycle from concept, development, testing, and deployment, collaborating with designers, QA engineers, and stakeholders to deliver on time and within scope.",
      "Implementing and managing application deployments using CI/CD pipelines, containerization, and cloud platforms to ensure smooth releases and production stability.",
      "Enhancing application performance and load times through optimized database queries, caching strategies, and efficient server-side logic.",
      "Contributing to code reviews and mentoring junior developers, establishing best practices, and maintaining high code quality standards.",
      "Owning system architecture and technical design decisions, ensuring solutions are scalable, maintainable, and aligned with long-term business goals.",
      "Leading technical discussions and architectural reviews, evaluating trade-offs between performance, security, and development velocity.",
      "Monitoring production systems, analyzing logs and metrics, and resolving complex issues to ensure high availability and reliability.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Postgresql",
      "MongoDB",
      "Prisma ORM",
      "Docker",
      "Git",
      "AWS",
    ],
    website: "https://www.linkedin.com/company/vervsocial/posts/?feedView=all",
    featured: true,
  },
  {
    id: 2,
    type: "work",
    company: "Verv",
    position: "Full-stack Developer",
    location: "Highbury Corner, N5 1RA, London , UK",
    period: "Dec 2024 - Nov 2025",
    duration: "1 year",
    description:
      "As a full-stack Developer, I am responsible for designing, developing, and optimizing scalable web applications, ensuring seamless data management, and collaborating with cross-functional teams to enhance system performance and user experience.",
    achievements: [
      "Building and maintaining scalable frontend components with React.js and Next.js to deliver responsive, user-friendly interfaces.",
      "Developing and optimizing backend systems with Node.js, Express.js, and Prisma ORM to ensure scalability, reliability, and security.",
      "Designing and implementing RESTful API endpoints to enable seamless communication between services.",
      "Integrating and managing relational (PostgreSQL) and NoSQL (MongoDB) databases to ensure secure, efficient, and scalable data handling.",
      "Leading projects across the full lifecycle from concept, development, testing, and deployment, collaborating with designers, QA engineers, and stakeholders to deliver on time and within scope.",
      "Implementing and managing application deployments using CI/CD pipelines, containerization, and cloud platforms to ensure smooth releases and production stability.",
      "Enhancing application performance and load times through optimized database queries, caching strategies, and efficient server-side logic.",
      "Contributing to code reviews and mentoring junior developers, establishing best practices, and maintaining high code quality standards.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Postgresql",
      "MongoDB",
      "Prisma ORM",
      "Docker",
      "Git",
      "AWS",
    ],
    website: "https://www.linkedin.com/company/vervsocial/posts/?feedView=all",
    featured: true,
  },
  {
    id: 3,
    type: "work",
    company: "Shafi Consultancy Limited",
    position: "Back End Developer",
    location: "Sylhet, Bangladesh",
    period: "Feb 2022 - Dec 2024",
    duration: "2 years 11 months",
    description:
      "Delivered scalable backend solutions focused on security, performance, and reliability. Experienced in developing RESTful APIs, managing relational and NoSQL databases, and integrating third-party services to support high-traffic business applications.",
    achievements: [
      "Improved API performance by refactoring endpoints in Node.js (Express) and optimizing database queries in PostgreSQL/MongoDB.",
      "Reduced server response time through caching strategies, indexing, and query optimization.",
      "Designed and deployed secure authentication with JWT systems, cutting unauthorized access attempts.",
      " Built and maintained data-driven web applications with React and Node.js, enhancing system scalability and user experience.",
      "Wrote modular, reusable Python scripts for automation, ETL, and data processing, reducing manual work and improving efficiency.",
      "Integrated APIs with PostgreSQL and MongoDB to power dynamic dashboards.",
      "Provided mentorship and training to team members, including leading sessions on Python to enhance team-wide technical skills.",
      "Conduct training sessions on Python to enhance team skill sets.",
      "Read and analyze client requirements for data transformations and statistical analysis.",
      "UDevelop and validate programs in appropriate software to deliver outputs within agreed timelines and budget.",
    ],
    technologies: ["Node.js", "Express.js", "Next.js", "React.js", "Git"],
    website: "https://www.shaficonsultancy.com",
    featured: false,
  },
  {
    id: 4,
    type: "work",
    company: "Shafi Consultancy Limited",
    position: "Trainee Statistical Programmer",
    location: "Sylhet, Bangladesh",
    period: "Aug 2021 - Jan 2022",
    duration: "6 months",
    description: "I was responsible for",
    achievements: [
      "Read, understand, and complete training on all assigned SOPs, Guidelines, and Working Instructions.",
      "Received training on clinical trials, data manipulation, SAS programming, and NONMEM.",
      "Developed and maintained well-documented programs for statistical analysis.",
      "Gained hands-on experience in data processing and statistical programming techniques.",
      "Learned best practices for ensuring data integrity and compliance with industry standards.",
    ],
    technologies: [
      "Python",
      "SAS",
      "Data Visualization",
      "Data Analysis",
      "Quality Assurance",
    ],
    website: "https://www.shaficonsultancy.com",
    featured: false,
  },
  {
    id: 5,
    type: "education",
    company: "Shahjalal University of Science and Technologyy",
    position: "Bachelor of Science in Mathematics",
    location: "Sylhet, Bangladesh",
    period: "2015 - 2019",
    duration: "4 years",
    description:
      "Focused on Mathematics. Explored the intersection of technology and art through various projects and research.",
    achievements: ["Led the Euclid Programming Club with 200+ members"],
    technologies: [
      "Python",
      "C",
      "Machine Learning",
      "Data Structures",
      "Algorithms",
    ],
    website: "https://www.sust.edu",
    featured: false,
  },
];

export const skills = [
  {
    category: "Frontend",
    items: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Tailwind CSS",
      "Vanila CSS",
      "Zustand",
    ],
  },
  {
    category: "Creative",
    items: ["Axios", "Tanstack Query", "React-hook-form", "Zod", "JWT"],
  },
  {
    category: "Backend",
    items: ["Node.js", "Express.js", "Python", "PostgreSQL", "MongoDB"],
  },
  {
    category: "Tools",
    items: ["Git", "GitHub", "Docker", "AWS", "VS Code"],
  },
];

export const categories = [
  { key: "all", label: "All Experience" },
  { key: "work", label: "Work" },
  { key: "education", label: "Education" },
];
